export const currencies = [
  { code: "AFN", name: "Afghan Afghani", value: "؋" },
  { code: "EUR", name: "Euro", value: "€" },
  { code: "ALL", name: "Albanian Lek", value: "L" },
  { code: "DZD", name: "Algerian Dinar", value: "د.ج" },
  { code: "USD", name: "United States Dollar", value: "$" },
  { code: "AOA", name: "Angolan Kwanza", value: "Kz" },
  { code: "XCD", name: "East Caribbean Dollar", value: "$" },
  { code: "ARS", name: "Argentine Peso", value: "$" },
  { code: "AMD", name: "Armenian Dram", value: "֏" },
  { code: "AWG", name: "Aruban Florin", value: "ƒ" },
  { code: "AUD", name: "Australian Dollar", value: "A$" },
  { code: "AZN", name: "Azerbaijani Manat", value: "₼" },
  { code: "BSD", name: "Bahamian Dollar", value: "$" },
  { code: "BHD", name: "Bahraini Dinar", value: ".د.ب" },
  { code: "BDT", name: "Bangladeshi Taka", value: "৳" },
  { code: "BBD", name: "Barbadian Dollar", value: "$" },
  { code: "BYN", name: "Belarusian Ruble", value: "Br" },
  { code: "BZD", name: "Belize Dollar", value: "$" },
  { code: "XOF", name: "West African CFA Franc", value: "Fr" },
  { code: "BMD", name: "Bermudian Dollar", value: "$" },
  { code: "INR", name: "Indian Rupee", value: "₹" },
  { code: "BTN", name: "Bhutanese Ngultrum", value: "Nu." },
  { code: "BOB", name: "Bolivian Boliviano", value: "Bs." },
  { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", value: "KM" },
  { code: "BWP", name: "Botswana Pula", value: "P" },
  { code: "NOK", name: "Norwegian Krone", value: "kr" },
  { code: "BRL", name: "Brazilian Real", value: "R$" },
  { code: "BND", name: "Brunei Dollar", value: "$" },
  { code: "BGN", name: "Bulgarian Lev", value: "лв" },
  { code: "BIF", name: "Burundian Franc", value: "Fr" },
  { code: "KHR", name: "Cambodian Riel", value: "៛" },
  { code: "XAF", name: "Central African CFA Franc", value: "Fr" },
  { code: "CAD", name: "Canadian Dollar", value: "C$" },
  { code: "CVE", name: "Cape Verdean Escudo", value: "$" },
  { code: "KYD", name: "Cayman Islands Dollar", value: "$" },
  { code: "CLP", name: "Chilean Peso", value: "$" },
  { code: "CNY", name: "Chinese Yuan", value: "¥" },
  { code: "COP", name: "Colombian Peso", value: "$" },
  { code: "KMF", name: "Comorian Franc", value: "Fr" },
  { code: "CDF", name: "Congolese Franc", value: "Fr" },
  { code: "CRC", name: "Costa Rican Colón", value: "₡" },
  { code: "HRK", name: "Croatian Kuna", value: "kn" },
  { code: "CUP", name: "Cuban Peso", value: "$" },
  { code: "CZK", name: "Czech Koruna", value: "Kč" },
  { code: "DKK", name: "Danish Krone", value: "kr" },
  { code: "DJF", name: "Djiboutian Franc", value: "Fr" },
  { code: "DOP", name: "Dominican Peso", value: "$" },
  { code: "EGP", name: "Egyptian Pound", value: "£" },
  { code: "ERN", name: "Eritrean Nakfa", value: "Nfk" },
  { code: "ETB", name: "Ethiopian Birr", value: "Br" },
  { code: "FJD", name: "Fijian Dollar", value: "$" },
  { code: "XPF", name: "CFP Franc", value: "Fr" },
  { code: "GMD", name: "Gambian Dalasi", value: "D" },
  { code: "GEL", name: "Georgian Lari", value: "₾" },
  { code: "GHS", name: "Ghanaian Cedi", value: "₵" },
  { code: "GIP", name: "Gibraltar Pound", value: "£" },
  { code: "GTQ", name: "Guatemalan Quetzal", value: "Q" },
  { code: "GNF", name: "Guinean Franc", value: "Fr" },
  { code: "GYD", name: "Guyanese Dollar", value: "$" },
  { code: "HTG", name: "Haitian Gourde", value: "G" },
  { code: "HNL", name: "Honduran Lempira", value: "L" },
  { code: "HKD", name: "Hong Kong Dollar", value: "HK$" },
  { code: "HUF", name: "Hungarian Forint", value: "Ft" },
  { code: "ISK", name: "Icelandic Króna", value: "kr" },
  { code: "IDR", name: "Indonesian Rupiah", value: "Rp" },
  { code: "IRR", name: "Iranian Rial", value: "﷼" },
  { code: "IQD", name: "Iraqi Dinar", value: "ع.د" },
  { code: "ILS", name: "Israeli New Shekel", value: "₪" },
  { code: "JMD", name: "Jamaican Dollar", value: "J$" },
  { code: "JPY", name: "Japanese Yen", value: "¥" },
  { code: "JOD", name: "Jordanian Dinar", value: "د.ا" },
  { code: "KZT", name: "Kazakhstani Tenge", value: "₸" },
  { code: "KES", name: "Kenyan Shilling", value: "Sh" },
  { code: "KWD", name: "Kuwaiti Dinar", value: "د.ك" },
  { code: "KGS", name: "Kyrgyzstani Som", value: "с" },
  { code: "LAK", name: "Lao Kip", value: "₭" },
  { code: "LBP", name: "Lebanese Pound", value: "ل.ل" },
  { code: "LSL", name: "Lesotho Loti", value: "L" },
  { code: "LRD", name: "Liberian Dollar", value: "$" },
  { code: "LYD", name: "Libyan Dinar", value: "ل.د" },
  { code: "MOP", name: "Macanese Pataca", value: "P" },
  { code: "MKD", name: "Macedonian Denar", value: "ден" },
  { code: "MGA", name: "Malagasy Ariary", value: "Ar" },
  { code: "MWK", name: "Malawian Kwacha", value: "MK" },
  { code: "MYR", name: "Malaysian Ringgit", value: "RM" },
  { code: "MVR", name: "Maldivian Rufiyaa", value: "ރ" },
  { code: "MRU", name: "Mauritanian Ouguiya", value: "UM" },
  { code: "MUR", name: "Mauritian Rupee", value: "₨" },
  { code: "MXN", name: "Mexican Peso", value: "$" },
  { code: "MDL", name: "Moldovan Leu", value: "L" },
  { code: "MNT", name: "Mongolian Tögrög", value: "₮" },
  { code: "MAD", name: "Moroccan Dirham", value: "د.م." },
  { code: "MZN", name: "Mozambican Metical", value: "MT" },
  { code: "MMK", name: "Myanmar Kyat", value: "K" },
  { code: "NAD", name: "Namibian Dollar", value: "$" },
  { code: "NPR", name: "Nepalese Rupee", value: "₨" },
  { code: "ANG", name: "Netherlands Antillean Guilder", value: "ƒ" },
  { code: "NZD", name: "New Zealand Dollar", value: "NZ$" },
  { code: "NIO", name: "Nicaraguan Córdoba", value: "C$" },
  { code: "NGN", name: "Nigerian Naira", value: "₦" },
  { code: "OMR", name: "Omani Rial", value: "ر.ع." },
  { code: "PKR", name: "Pakistani Rupee", value: "₨" },
  { code: "PAB", name: "Panamanian Balboa", value: "B/." },
  { code: "PGK", name: "Papua New Guinean Kina", value: "K" },
  { code: "PYG", name: "Paraguayan Guaraní", value: "₲" },
  { code: "PEN", name: "Peruvian Sol", value: "S/" },
  { code: "PHP", name: "Philippine Peso", value: "₱" },
  { code: "PLN", name: "Polish Zloty", value: "zł" },
  { code: "QAR", name: "Qatari Riyal", value: "ر.ق" },
  { code: "RON", name: "Romanian Leu", value: "lei" },
  { code: "RUB", name: "Russian Ruble", value: "₽" },
  { code: "RWF", name: "Rwandan Franc", value: "Fr" },
  { code: "SHP", name: "Saint Helena Pound", value: "£" },
  { code: "WST", name: "Samoan Tala", value: "T" },
  { code: "STN", name: "São Tomé and Príncipe Dobra", value: "Db" },
  { code: "SAR", name: "Saudi Riyal", value: "﷼" },
  { code: "RSD", name: "Serbian Dinar", value: "дин" },
  { code: "SCR", name: "Seychellois Rupee", value: "₨" },
  { code: "SLL", name: "Sierra Leonean Leone", value: "Le" },
  { code: "SGD", name: "Singapore Dollar", value: "S$" },
  { code: "SBD", name: "Solomon Islands Dollar", value: "$" },
  { code: "SOS", name: "Somali Shilling", value: "Sh" },
  { code: "ZAR", name: "South African Rand", value: "R" },
  { code: "KRW", name: "South Korean Won", value: "₩" },
  { code: "SSP", name: "South Sudanese Pound", value: "£" },
  { code: "LKR", name: "Sri Lankan Rupee", value: "Rs" },
  { code: "SDG", name: "Sudanese Pound", value: "ج.س." },
  { code: "SRD", name: "Surinamese Dollar", value: "$" },
  { code: "SZL", name: "Swazi Lilangeni", value: "L" },
  { code: "SEK", name: "Swedish Krona", value: "kr" },
  { code: "CHF", name: "Swiss Franc", value: "CHF" },
  { code: "SYP", name: "Syrian Pound", value: "£" },
  { code: "TWD", name: "New Taiwan Dollar", value: "NT$" },
  { code: "TJS", name: "Tajikistani Somoni", value: "SM" },
  { code: "TZS", name: "Tanzanian Shilling", value: "Sh" },
  { code: "THB", name: "Thai Baht", value: "฿" },
  { code: "TOP", name: "Tongan Paʻanga", value: "T$" },
  { code: "TTD", name: "Trinidad and Tobago Dollar", value: "$" },
  { code: "TND", name: "Tunisian Dinar", value: "د.ت" },
  { code: "TRY", name: "Turkish Lira", value: "₺" },
  { code: "TMT", name: "Turkmenistani Manat", value: "m" },
  { code: "UGX", name: "Ugandan Shilling", value: "Sh" },
  { code: "UAH", name: "Ukrainian Hryvnia", value: "₴" },
  { code: "AED", name: "United Arab Emirates Dirham", value: "د.إ" },
  { code: "UYU", name: "Uruguayan Peso", value: "$" },
  { code: "UZS", name: "Uzbekistani Som", value: "сўм" },
  { code: "VUV", name: "Vanuatu Vatu", value: "Vt" },
  { code: "VES", name: "Venezuelan Bolívar", value: "Bs.S" },
  { code: "VND", name: "Vietnamese Dong", value: "₫" },
  { code: "YER", name: "Yemeni Rial", value: "﷼" },
  { code: "ZMW", name: "Zambian Kwacha", value: "ZK" },
  { code: "ZWL", name: "Zimbabwean Dollar", value: "$" },
];
