export const dateFormats = [
  "YYYY-MM-DD",
  "MM-DD-YYYY",
  "DD-MM-YYYY",
  "YYYY/MM/DD",
  "MM/DD/YYYY",
  "DD/MM/YYYY",
  "YYYY.MM.DD",
  "MM.DD.YYYY",
  "DD.MM.YYYY",
  "DD-MMM-YYYY",
  "MMM DD, YYYY",
  "MMMM DD, YYYY",
  "DD MMM YYYY",
  "DD MMMM YYYY",
  "YYYYMMDD",
  "MMDDYYYY",
  "DDMMYYYY",
  "YYYY/MM/DD hh:mm:ss",
  "MM/DD/YYYY hh:mm:ss A",
  "DD/MM/YYYY HH:mm:ss",
  "MMM DD, YYYY hh:mm:ss A",
  "dddd, MMMM DD, YYYY",
  "YYYY-MM-DDTHH:mm:ssZ",
  "YYYY-MM-DDTHH:mm:ss.SSSZ",
  "YYYY-MM-DD HH:mm:ss",
  "MM-DD-YYYY hh:mm A",
  "DD-MM-YYYY hh:mm A",
  "ddd, DD MMM YYYY HH:mm:ss GMT",
  "dddd, DD-MMM-YY HH:mm:ss Z",
];
